/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description List conversations for the configured local user.
         */
        get: operations["list_conversations_conversations_get"];
        put?: never;
        /**
         * Create Conversation
         * @description Create a conversation in a local user's scope.
         */
        post: operations["create_conversation_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Conversation
         * @description Delete a local user's conversation.
         */
        delete: operations["delete_conversation_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}/assistant-response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Assistant Response
         * @description Generate and persist one assistant response for a local conversation.
         */
        post: operations["create_assistant_response_conversations__conversation_id__assistant_response_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}/assistant-response/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Assistant Response
         * @description Stream and persist one assistant response for a local conversation.
         */
        post: operations["stream_assistant_response_conversations__conversation_id__assistant_response_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description List messages for a local user's conversation.
         */
        get: operations["list_messages_conversations__conversation_id__messages_get"];
        put?: never;
        /**
         * Create Message
         * @description Append a message and retrieval episode for a local user's conversation.
         */
        post: operations["create_message_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return a minimal local readiness signal.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrieval/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Retrieval
         * @description Search memories inside one local scope.
         */
        post: operations["search_retrieval_retrieval_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scopes
         * @description List scopes for the configured local user.
         */
        get: operations["list_scopes_scopes_get"];
        put?: never;
        /**
         * Create Scope
         * @description Create a scope for the configured local user.
         */
        post: operations["create_scope_scopes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssistantGenerationResponse
         * @description HTTP representation of a generated assistant response.
         */
        AssistantGenerationResponse: {
            assistant_message: components["schemas"]["MessageResponse"];
            /** Chat Model */
            chat_model: string;
            /** Finish Reason */
            finish_reason: string | null;
            /** Used Memory Episode Ids */
            used_memory_episode_ids: string[];
        };
        /**
         * ConversationResponse
         * @description HTTP representation of a conversation.
         */
        ConversationResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Scope Id
             * Format: uuid
             */
            scope_id: string;
            /** Title */
            title: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CreateAssistantResponseBody
         * @description Request body for creating a local assistant response.
         */
        CreateAssistantResponseBody: {
            /**
             * Max Prompt Chars
             * @default 16000
             */
            max_prompt_chars: number;
            /**
             * Query Message Id
             * Format: uuid
             */
            query_message_id: string;
            /**
             * Recent Message Limit
             * @default 20
             */
            recent_message_limit: number;
            /**
             * Scope Id
             * Format: uuid
             */
            scope_id: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /**
         * CreateConversationBody
         * @description Request body for creating a conversation in an existing scope.
         */
        CreateConversationBody: {
            /**
             * Scope Id
             * Format: uuid
             */
            scope_id: string;
            /** Title */
            title?: string | null;
        };
        /**
         * CreateMessageBody
         * @description Request body for appending a message and retrieval episode.
         */
        CreateMessageBody: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant";
            /** Token Count */
            token_count: number;
        };
        /**
         * CreateScopeBody
         * @description Request body for creating a local memory scope.
         */
        CreateScopeBody: {
            /** Name */
            name: string;
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
        };
        /**
         * CreatedMessageResponse
         * @description HTTP representation of a message created with its retrieval episode.
         */
        CreatedMessageResponse: {
            /** Content */
            content: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Episode Id
             * Format: uuid
             */
            episode_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Position */
            position: number;
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant";
            /** Token Count */
            token_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Local API health status.
         */
        HealthResponse: {
            /**
             * Mode
             * @constant
             */
            mode: "local";
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * MessageResponse
         * @description HTTP representation of an immutable conversation message.
         */
        MessageResponse: {
            /** Content */
            content: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Position */
            position: number;
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant";
            /** Token Count */
            token_count: number;
        };
        /**
         * RetrievalSearchBody
         * @description Request body for scoped retrieval search.
         */
        RetrievalSearchBody: {
            /** Query */
            query: string;
            /**
             * Scope Id
             * Format: uuid
             */
            scope_id: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /**
         * ScopeResponse
         * @description HTTP representation of a memory scope.
         */
        ScopeResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** System Prompt */
            system_prompt: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ScoredEpisodeResponse
         * @description HTTP representation of one scored retrieval result.
         */
        ScoredEpisodeResponse: {
            /** Access Count */
            access_count: number;
            /** Access Score */
            access_score: number;
            /** Content */
            content: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Embedding Model Id */
            embedding_model_id: number;
            /** Frequency Score */
            frequency_score: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Importance */
            importance: number;
            /** Importance Score */
            importance_score: number;
            /** Kind */
            kind: string;
            /** Last Accessed At */
            last_accessed_at: string | null;
            /** Message Id */
            message_id: string | null;
            /** Message Position */
            message_position: number | null;
            /** Range End */
            range_end: number | null;
            /** Range Start */
            range_start: number | null;
            /** Recency Score */
            recency_score: number;
            /** Result Rank */
            result_rank: number;
            /**
             * Scope Id
             * Format: uuid
             */
            scope_id: string;
            /** Score */
            score: number;
            /** Similarity */
            similarity: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_conversations_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"][];
                };
            };
        };
    };
    create_conversation_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_assistant_response_conversations__conversation_id__assistant_response_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssistantResponseBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantGenerationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_assistant_response_conversations__conversation_id__assistant_response_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssistantResponseBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_conversations__conversation_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_message_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMessageBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    search_retrieval_retrieval_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalSearchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoredEpisodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scopes_scopes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeResponse"][];
                };
            };
        };
    };
    create_scope_scopes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScopeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
